Repository Quantas/shark-ng-table, pull requests merged in 2018-08, with the labels that each got.

#100 fix(columns): Make column picker a flexbox to reduce column length
  CHANGELOG.md
  docs/3rdpartylicenses.txt
  docs/assets/style/shark-ng-table.css
  docs/index.html
  docs/inline.576e0cf07e8aa93b97a9.bundle.js
  docs/inline.fedab42f8e98a0e6ad50.bundle.js
  docs/main.7011dc073480ce4ccbfd.bundle.js
  docs/main.bebda9e7d5a3c09f6b5c.bundle.js
  docs/styles.f3118f3aa28e5b82c96f.bundle.css
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/samples/large.component.ts
  src/app/table/column-dropdown.component.ts
  src/app/table/style/shark-ng-table.css
  src/app/test/table.component.column-picker.spec.ts
Labels: accessibility, enhancement

#107 Content Projection
  CHANGELOG.md
  docs/assets/style/shark-ng-table.css
  docs/index.html
  docs/inline.11eab169f2b2b7a80f2f.bundle.js
  docs/inline.77071a459a6e85ef3c68.bundle.js
  docs/main.7855b7d79f9bfeb3739f.bundle.js
  docs/main.7bf665f12a2787208935.bundle.js
  docs/styles.4cf5df93fa075a7b4406.bundle.css
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/samples/content-projection.component.ts
  src/app/samples/everything.component.ts
  src/app/table/column-dropdown.component.ts
  src/app/table/index.ts
  src/app/table/style/shark-ng-table.css
  src/app/table/table.component.ts
  src/app/table/table.footer.component.ts
  src/app/table/table.info.header.component.ts
  src/app/table/table.module.ts
  src/app/test/table.component.column-picker.spec.ts
  src/app/test/table.pagination.component.spec.ts
Labels: accessibility, bug, enhancement

#109 CSS Prefixing
  CHANGELOG.md
  package.json
  src/app/app.component.ts
  src/app/samples/basic.component.ts
  src/app/samples/child-rows.component.ts
  src/app/samples/custom-cell.component.ts
  src/app/samples/data-export.component.ts
  src/app/samples/everything.component.ts
  src/app/samples/two-tables.component.ts
  src/app/table/style/shark-ng-table.css
  src/app/table/table.component.ts
Labels: bug, enhancement
